name = "ernisto/ro_sync"
version = "0.1.0-alpha.1"
license = "MIT"
includes = [
  "cli.luau",
  "utils/**",
  "lib/**",
  "pesde.toml",
  "README.md",
  "LICENSE",
  ".luaurc",
]

[target]
environment = "lune"
lib = "lib/init.luau"
bin = "cli.luau"

[engines]
pesde = "^0.7.0"
lune = "^0.10.4"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
ro_cloud = { name = "ernisto/ro_cloud", version = "=0.1.0-alpha.10" }
